lzc-sdk-version: "0.1"
name: LibreTV
package: cloud.lazycat.app.libretv
version: 0.0.5
description: 免费在线视频搜索与观看平台
homepage: https://github.com/bestZwei/LibreTV
author: bestZwei
application:
  subdomain: libretv
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://libretv:80/
services:
  libretv:
    image: registry.lazycat.cloud/czyt/bestzwei/libretv:3f3022c8c1681cdc
