lzc-sdk-version: "0.1"
name: LibreTV
package: cloud.lazycat.app.libretv
version: 0.0.9
description: 免费在线视频搜索与观看平台
homepage: https://github.com/bestZwei/LibreTV
author: bestZwei
application:
    subdomain: libretv
    background_task: false
    multi_instance: false
    gpu_accel: false
    kvm_accel: false
    usb_accel: false
    public_path:
        - /
    routes:
        - /=http://libretv:8080/
services:
    libretv:
        # bestzwei/libretv:latest
        image: https://coco.edu.deal:27908/s/default/af2c2a1b0775eea9d1dd49ed7781eed7
